name: CI
on: [push, pull_request]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2'
      - run: go build
