name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Golang Action
      uses: cedrickring/golang-action@1.3.0
      with:
        args: go build cmd/secpass/secpass.go
